### ISSUE TITLE
Crusher V1 will converted into Crusher V2

### ISSUE THREAD

**Issue by Buuub** [judos/hardCrafting#11] opened 2016-05-14 20:17 UTC
First of all please excuse my bad english. I'm from Germany and never had English in school :)
I think, i've found a bug in the mod.
On my Map are two Crusher V1 and in my inventory are one Crusher V2.
When i move the two Crusher V1 from the map to the inventory, there are three Crusher V2 und no Crusher V1. I think, this is not logical.

Buuub / Ralf

**Comment by judos** [comment] 2016-05-14 22:13
Hi Ralf,
No worries your English reads pretty good :)
With the update 0.3.11 I wanted to change the crushers to be an assembling machine (let's you select the recipe) instead of a furnace (immediately works depending on input). However changing the type of a building crashes factorio. So instead I left the old crusher in the game. All items are converted into crusher v2. However old crusher buildings remain. Therefore I set that when you pick up an old crusher it will give you the new Crusher. The intention is that eventually everyone will just have the new crusher and then I can remove the old one totally. I did this mainly because people requested that the machine is more self explaining when it let's you select a recipe.
Hope this clears your question.
I will close this issue since it's not a bug but a feature :D
Cheers,
judos

**Closed as completed by judos** 2016-05-14 22:13 UTC
