### ISSUE TITLE
Incinerators can incinerate fuel

### ISSUE THREAD

**Issue by Dr-Jones** [judos/hardCrafting#22] opened 2017-03-31 15:30 UTC
The code that adds the recipes for incinerating things in incinerators also add this recipe for coal and coal-dust. This makes it impossible to automatically fuel a non-electric incinerator.

Please update the code to not add this recipe for (at least) coal and coal-dust, so fueling the incinerator in the early game becomes easier.

Thanks!

**Comment by judos** [comment] 2017-04-02 11:30
Thanks for the report.
The issue is fixed and will be released with the next version. (0.5.2)

**Closed as completed by judos** 2017-04-02 11:30 UTC
